# Generated by Django 5.2.4 on 2025-10-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_alter_customuser_role_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(default='customer', max_length=50),
        ),
    ]
