# Generated by Django 5.2.4 on 2025-10-19 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_active_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Only letters, spaces, and hyphens allowed.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Only letters, spaces, and hyphens allowed.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only letters, spaces, and hyphens allowed.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only letters, spaces, and hyphens allowed.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Valid Indian number required.', regex='^(\\+91[\\-\\s]?|0)?[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Valid 6-digit Indian pincode required.', regex='^[1-9][0-9]{5}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Only letters, spaces, and hyphens allowed.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
    ]
