# Generated by Django 5.2.4 on 2025-11-20 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_city_alter_customuser_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Indian number. Examples: '+919876543210', '09876543210', '9876543210'.", regex='^(\\+91[\\-\\s]?|0)?[6-9]\\d{9}$')]),
        ),
    ]
