# Generated by Django 5.2.4 on 2025-12-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('customer', 'Customer'), ('promoter', 'Promoter'), ('admin', 'Admin'), ('investor', 'Investor'), ('manager', 'Manager')], max_length=50, unique=True),
        ),
    ]
