# Generated by Django 5.2.4 on 2025-10-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0002_remove_promoter_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='promoter_type',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='promoter',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='promoter.promoter'),
        ),
        migrations.AddField(
            model_name='promotercommission',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
