# Generated by Django 5.2.4 on 2025-10-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0003_promoter_promoter_type_promoter_referred_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(help_text='1 = Direct promoter, 2 = Parent, 3 = Grandparent, etc.', unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage of total commission for this level', max_digits=5)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='promoter',
            name='premium_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
