# Generated by Django 5.2.4 on 2025-10-14 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant_promoter_commission_rate'),
        ('promoter', '0004_commissionlevel_promoter_premium_activated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='promoter.promoter')),
            ],
        ),
        migrations.CreateModel(
            name='PromotedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_by', to='products.productvariant')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_products', to='promoter.promoter')),
            ],
            options={
                'unique_together': {('promoter', 'product_variant')},
            },
        ),
    ]
