# Generated by Django 5.2.4 on 2025-10-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0005_premiumsettings_promoterpayment_promotedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='promoter',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='promoter',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='promoter',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
