# Generated by Django 5.2.4 on 2025-10-15 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0006_alter_promoter_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='phone_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit number', regex='^[6-9]\\d{9}$')]),
        ),
    ]
