# Generated by Django 5.2.4 on 2025-10-15 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0007_alter_promoter_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoter',
            name='application_status',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='approved_at',
        ),
    ]
