# Generated by Django 5.2.4 on 2025-10-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0008_remove_promoter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsettings',
            name='offer_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='premiumsettings',
            name='offer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='premiumsettings',
            name='offer_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premiumsettings',
            name='offer_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
