# Generated by Django 5.2.4 on 2025-11-18 17:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0011_withdrawalrequest_processed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionlevel',
            name='level',
            field=models.PositiveIntegerField(help_text='1 = Direct, 2 = Parent, etc.', unique=True),
        ),
        migrations.AlterField(
            model_name='commissionlevel',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text='Percentage of total commission', max_digits=5),
        ),
        migrations.AlterField(
            model_name='promotedproduct',
            name='total_commission_generated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='promotercommission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('reversed', 'Reversed')], default='pending', max_length=20),
        ),
    ]
