# Generated by Django 5.2.4 on 2025-11-19 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0012_alter_commissionlevel_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit number', regex='^[6-9]\\d{9}$')]),
        ),
    ]
