# Generated by Django 5.2.4 on 2025-11-20 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0013_alter_promoter_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit number', regex='^[6-9]\\d{9}$')]),
        ),
    ]
