# Generated by Django 5.2.4 on 2025-11-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0014_alter_promoter_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='total_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
