# Generated by Django 5.2.4 on 2025-11-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0015_promoter_total_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoter',
            name='total_clicks',
        ),
    ]
