# Generated by Django 5.2.4 on 2025-12-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0016_remove_promoter_total_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='razorpay_payout_id',
        ),
    ]
