# Generated by Django 5.2.4 on 2025-12-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0017_remove_withdrawalrequest_processed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
