# Generated by Django 5.2.4 on 2025-12-23 12:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_contactmessage'),
        ('promoter', '0018_alter_withdrawalrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='premiumsettings',
            old_name='amount',
            new_name='annual_amount',
        ),
        migrations.RenameField(
            model_name='premiumsettings',
            old_name='offer_amount',
            new_name='annual_offer',
        ),
        migrations.RenameField(
            model_name='promoter',
            old_name='is_eligible_for_withdrawal',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='promoterpayment',
            old_name='premium_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='promoterpayment',
            old_name='payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='premiumsettings',
            name='active',
        ),
        migrations.RemoveField(
            model_name='premiumsettings',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='total_sales_count',
        ),
        migrations.RemoveField(
            model_name='promoterpayment',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='premiumsettings',
            name='monthly_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premiumsettings',
            name='monthly_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='promoter',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promoter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='promotercommission',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_link_code', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='promoter.promoter')),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='promoter.promoter')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_ads', to='promoter.promoter')),
            ],
        ),
        migrations.CreateModel(
            name='PromoterReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tier_at_referral', models.CharField(default='free', max_length=20)),
                ('current_tier', models.CharField(default='free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_promoter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_entry', to='promoter.promoter')),
                ('referrer_promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='promoter.promoter')),
            ],
            options={
                'db_table': 'promoter_referrals',
                'constraints': [models.UniqueConstraint(fields=('referred_promoter',), name='unique_referred_promoter')],
            },
        ),
    ]
