# Generated by Django 5.2.4 on 2025-12-23 14:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_replacementrequest_waybill_and_more'),
        ('products', '0011_delete_contactmessage'),
        ('promoter', '0019_referralcommissionsetting_subscriptionsetting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoter',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='promotercommission',
            name='earning_type',
            field=models.CharField(choices=[('direct_sale', 'Direct Sale'), ('referral_sale', 'Referral Sale'), ('subscription_referral', 'Subscription Referral'), ('tier_bonus', 'Tier Bonus')], default='direct_sale', max_length=30),
        ),
        migrations.AddField(
            model_name='promotercommission',
            name='referral_source_promoter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_referral_commissions', to='promoter.promoter'),
        ),
        migrations.AddField(
            model_name='promotercommission',
            name='referral_source_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promoter.subscription'),
        ),
        migrations.AddField(
            model_name='promoterreferral',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promoterreferral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='referred_by_promoter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_subscriptions', to='promoter.promoter'),
        ),
        migrations.AlterField(
            model_name='promotercommission',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='promotercommission',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PromoterBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z .]+$')])),
                ('account_number', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(regex='^\\d{9,18}$')])),
                ('ifsc_code', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('bank_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z ]+$')])),
                ('is_verified', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('promoter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='promoter.promoter')),
            ],
        ),
    ]
