# Generated by Django 5.2.4 on 2025-12-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0020_remove_promoter_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
