# Generated by Django 5.2.4 on 2025-12-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0022_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotercommission',
            name='pending_reason',
            field=models.CharField(blank=True, choices=[('subscription_inactive', 'Subscription Inactive'), ('order_not_completed', 'Order Not Completed'), ('manual_hold', 'Manual Hold')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='promotercommission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
