# Generated by Django 5.2.4 on 2025-12-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0023_promotercommission_pending_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='total_sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
