# Generated by Django 5.2.4 on 2026-02-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0024_promoter_total_sales_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsettings',
            name='singleton',
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
