# Generated by Django 5.2.4 on 2025-10-12 03:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('payment_method', models.CharField(choices=[('Razorpay', 'Razorpay')], default='Razorpay', max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_link', models.URLField(blank=True, null=True)),
                ('handoff_timestamp', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('promoter_id', models.IntegerField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.courierservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number', regex='^[6-9]\\d{9}$')])),
                ('address', models.TextField()),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, and hyphens.', regex='^[A-Za-z\\s\\-]+$')])),
                ('state', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, and hyphens.', regex='^[A-Za-z\\s\\-]+$')])),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit postal code', regex='^\\d{6}$')])),
                ('country', models.CharField(default='India', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.shippingaddress'),
        ),
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('admin_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('variant_policy_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('new_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_origin', to='orders.order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='orders.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['delivered', 'failed', 'rejected']), _negated=True), fields=('order_item',), name='unique_active_replacement_per_item')],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('manual', 'Manual')], default='razorpay', max_length=20)),
                ('user_upi', models.CharField(blank=True, default='', max_length=100)),
                ('admin_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('admin_processed_at', models.DateTimeField(blank=True, null=True)),
                ('variant_policy_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'refunded'), _negated=True), fields=('order_item',), name='unique_active_return_per_item')],
            },
        ),
    ]
