# Generated by Django 5.2.4 on 2025-10-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
