# Generated by Django 5.2.4 on 2025-10-12 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shippingaddress_district_shippingaddress_region'),
        ('promoter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promoter_id',
        ),
        migrations.AddField(
            model_name='order',
            name='promoter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promoter.promoter'),
        ),
    ]
