# Generated by Django 5.2.4 on 2025-10-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_cancel_reason_orderitem_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waybill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
