# Generated by Django 5.2.4 on 2025-10-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_is_refunded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_link',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
    ]
