# Generated by Django 5.2.4 on 2025-10-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_tracking_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='handoff_timestamp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='waybill',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='courier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='handoff_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='waybill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
