# Generated by Django 5.2.4 on 2025-10-29 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_courier_remove_order_handoff_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_refunded',
            new_name='has_refund',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refunded_at',
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
            ],
        ),
    ]
