# Generated by Django 5.2.4 on 2025-10-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_label_generated_at_orderitem_label_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='admin_decision',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='refund_method',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='user_upi',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='variant_policy_snapshot',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='delivered_back_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='waybill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pickup_scheduled', 'Pickup Scheduled'), ('in_transit', 'In Transit'), ('delivered_to_warehouse', 'Delivered to Warehouse'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
