# Generated by Django 5.2.4 on 2025-11-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_returnrequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='handoff_timestamp',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='label_generated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='label_url',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shipped_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tracking_url',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='waybill',
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='handoff_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='label_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='label_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waybill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
