# Generated by Django 5.2.4 on 2025-11-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_orderitem_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier to link retries or failed payment sessions', max_length=100, null=True),
        ),
    ]
