# Generated by Django 5.2.4 on 2025-11-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_checkout_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCQuestionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_question_id', models.CharField(max_length=50, unique=True)),
                ('delhivery_question_id', models.CharField(max_length=50, unique=True)),
                ('question_text', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='qc_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='qc_form_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='qc_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
