# Generated by Django 5.2.4 on 2025-11-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_qcquestionmapping_returnrequest_qc_completed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QCQuestionMapping',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='qc_completed',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='qc_form_id',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='qc_result',
        ),
    ]
