# Generated by Django 5.2.4 on 2025-11-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_order_status_alter_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='recovery_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='return_charge_incurred',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
