# Generated by Django 5.2.4 on 2025-11-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_remove_returnrequest_blocked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='reverse_pickup_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
