# Generated by Django 5.2.4 on 2025-11-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_returnrequest_reverse_pickup_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='recovery_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
