# Generated by Django 5.2.4 on 2025-11-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_returnrequest_recovery_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
