# Generated by Django 5.2.4 on 2025-11-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_orderitem_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_commission_applied',
            field=models.BooleanField(default=False),
        ),
    ]
