# Generated by Django 5.2.4 on 2025-12-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_order_packed_at_order_pickup_request_order_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='warehouse',
        ),
    ]
