# Generated by Django 5.2.4 on 2025-12-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_remove_order_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('return_initiated', 'Return Initiated'), ('delivered_to_warehouse', 'Delivered to Warehouse'), ('cancelled', 'Cancelled'), ('undelivered', 'Undelivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('return_initiated', 'Return Initiated'), ('delivered_to_warehouse', 'Delivered to Warehouse'), ('cancelled', 'Cancelled'), ('undelivered', 'Undelivered'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
    ]
