# Generated by Django 5.2.4 on 2025-12-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_alter_order_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='packed_at',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
