# Generated by Django 5.2.4 on 2025-12-20 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_remove_order_packed_at_orderitem_packed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='replacementrequest',
            name='unique_active_replacement_per_item',
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='delhivery_status',
            field=models.CharField(blank=True, help_text='Delhivery Status (Open, Scheduled, In Transit, DTO, Canceled, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='delhivery_status_type',
            field=models.CharField(blank=True, help_text='Delhivery Status Type (PP, PU, DL, CN)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='delhivery_status_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when Delhivery sent this status', null=True),
        ),
        migrations.AlterField(
            model_name='replacementrequest',
            name='admin_decision',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='replacementrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('scheduled', 'Exchange Scheduled'), ('in_transit', 'Exchange In Transit'), ('completed', 'Exchange Completed'), ('cancelled', 'Exchange Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('manifested', 'Manifested'), ('not_picked', 'Not Picked'), ('in_transit', 'In Transit'), ('pending', 'Pending'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('rt_in_transit', 'Return In Transit'), ('rt_pending', 'Return Pending'), ('rt_dispatched', 'Return Dispatched'), ('rto', 'Returned to Origin'), ('pp_open', 'Pickup Open'), ('pp_scheduled', 'Pickup Scheduled'), ('pp_dispatched', 'Pickup Dispatched'), ('pu_in_transit', 'Pickup In Transit'), ('pu_pending', 'Pickup Pending'), ('pu_dispatched', 'Pickup Dispatched'), ('dto', 'Delivered to Origin'), ('canceled', 'Canceled'), ('closed', 'Closed')], default='pending', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='replacementrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['completed', 'failed', 'rejected', 'cancelled']), _negated=True), fields=('order_item',), name='unique_active_replacement_per_item'),
        ),
    ]
