# Generated by Django 5.2.4 on 2025-12-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_remove_replacementrequest_unique_active_replacement_per_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('return_initiated', 'Return Initiated'), ('delivered_to_warehouse', 'Delivered to Warehouse'), ('cancelled', 'Cancelled'), ('undelivered', 'Undelivered'), ('repl_scheduled', 'Replacement Scheduled'), ('repl_in_transit', 'Replacement In Transit'), ('repl_completed', 'Replacement Completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('return_initiated', 'Return Initiated'), ('delivered_to_warehouse', 'Delivered to Warehouse'), ('cancelled', 'Cancelled'), ('undelivered', 'Undelivered'), ('refunded', 'Refunded'), ('repl_scheduled', 'Replacement Scheduled'), ('repl_in_transit', 'Replacement In Transit'), ('repl_completed', 'Replacement Completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='replacementrequest',
            name='delhivery_status',
            field=models.TextField(blank=True, help_text='Raw Delhivery status or error message', null=True),
        ),
    ]
