# Generated by Django 5.2.4 on 2025-12-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_order_status_alter_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrecoverytransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='returnrecoverytransaction',
            name='source_type',
            field=models.CharField(choices=[('return', 'Return'), ('replacement', 'Replacement')], default='return', max_length=20),
        ),
    ]
