# Generated by Django 5.2.4 on 2025-12-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_returnrecoverytransaction_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementrequest',
            name='recovery_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='replacement_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
