# Generated by Django 5.2.4 on 2025-12-22 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_replacementrequest_recovery_fixed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='returnrequest',
            name='unique_active_return_per_item',
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pp_open', 'Pickup Open'), ('pp_scheduled', 'Pickup Scheduled'), ('pp_dispatched', 'Pickup Dispatched'), ('pu_in_transit', 'Pickup In Transit'), ('pu_pending', 'Pickup Pending'), ('pu_dispatched', 'Pickup Dispatched'), ('dto', 'Delivered to Origin'), ('refunded', 'Refunded'), ('canceled', 'Canceled'), ('closed', 'Closed')], default='pending', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('order_item__isnull', False), models.Q(('status', 'refunded'), _negated=True)), fields=('order_item',), name='unique_active_return_per_item'),
        ),
    ]
