# Generated by Django 5.2.4 on 2025-12-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_remove_returnrequest_unique_active_return_per_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementrequest',
            name='waybill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='delhivery_status',
            field=models.TextField(blank=True, help_text='Raw Delhivery status or error message', null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='delhivery_status_type',
            field=models.CharField(blank=True, help_text='Delhivery Status Type (RT, DL, etc.)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='delhivery_status_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when Delhivery sent this status', null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('pp_open', 'Pickup Open'), ('pp_scheduled', 'Pickup Scheduled'), ('pp_dispatched', 'Pickup Dispatched'), ('pu_in_transit', 'Pickup In Transit'), ('pu_pending', 'Pickup Pending'), ('pu_dispatched', 'Pickup Dispatched'), ('dto', 'Delivered to Origin'), ('refunded', 'Refunded'), ('canceled', 'Canceled'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('pickup_failed', 'Pickup Failed')], default='pp_open', max_length=50),
        ),
    ]
