# Generated by Django 5.2.4 on 2025-12-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_replacementrequest_waybill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promoter',
        ),
    ]
