# Generated by Django 5.2.4 on 2025-12-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_remove_order_promoter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_commission_applied',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_commission_applied',
            field=models.BooleanField(default=False),
        ),
    ]
