# Generated by Django 5.2.4 on 2025-10-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.FloatField(default=0.5),
        ),
    ]
