# Generated by Django 5.2.4 on 2025-10-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='promoter_commission_rate',
            field=models.FloatField(default=0.0, help_text='Fixed commission % for promoters on this product'),
        ),
    ]
