# Generated by Django 5.2.4 on 2025-10-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant_promoter_commission_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourierService',
        ),
    ]
