# Generated by Django 5.2.4 on 2025-11-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_courierservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='weight',
            field=models.FloatField(default=0.5, help_text='Enter weight in kilograms (e.g., 0.2 for 200g, 2 for 2kg)'),
        ),
    ]
