# Generated by Django 5.2.4 on 2025-12-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Enter weight in kilograms (e.g., 0.2 for 200g, 2 for 2kg)', max_digits=10),
        ),
    ]
