# Generated by Django 5.2.4 on 2025-12-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productvariant_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='promoter_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed commission % for promoters on this product', max_digits=5),
        ),
    ]
