# Generated by Django 5.2.4 on 2025-12-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
