# Generated by Django 5.2.4 on 2025-11-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
