# Generated by Django 5.2.4 on 2025-11-04 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        ('orders', '0019_order_checkout_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to='orders.orderitem'),
        ),
    ]
