# Generated by Django 5.2.4 on 2025-12-13 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_adminlog_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must exactly match Delhivery pickup_location (case-sensitive)', max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('country', models.CharField(default='India', max_length=50)),
                ('return_address', models.TextField()),
                ('return_city', models.CharField(max_length=50)),
                ('return_state', models.CharField(max_length=50)),
                ('return_pincode', models.CharField(max_length=6)),
                ('return_country', models.CharField(default='India', max_length=50)),
                ('delhivery_synced', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DelhiveryPickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField(db_index=True)),
                ('pickup_time', models.TimeField()),
                ('expected_package_count', models.PositiveIntegerField()),
                ('delhivery_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FAILED', 'Failed')], db_index=True, default='OPEN', max_length=10)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_requests', to='admin_dashboard.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'pickup_date')},
            },
        ),
    ]
