# Generated by Django 5.2.4 on 2025-12-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_warehouse_delhiverypickuprequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delhiverypickuprequest',
            options={'ordering': ['-pickup_date']},
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(db_index=True, help_text='Must exactly match Delhivery pickup_location (case-sensitive)', max_length=100, unique=True),
        ),
    ]
