# Generated by Django 5.2.4 on 2025-12-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_alter_delhiverypickuprequest_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='pincode',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='return_pincode',
            new_name='return_pin',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='delhivery_warehouse_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='last_sync_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
