# Generated by Django 5.2.4 on 2025-12-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_rename_pincode_warehouse_pin_and_more'),
        ('orders', '0031_remove_order_warehouse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='delhiverypickuprequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='delhiverypickuprequest',
            name='slot',
            field=models.CharField(choices=[('midday', 'Midday (10:00-14:00)'), ('evening', 'Evening (14:00-18:00)')], default='midday', max_length=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='delhiverypickuprequest',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='delhiverypickuprequest',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
