# Generated by Django 5.2.4 on 2025-12-16 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_alter_delhiverypickuprequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delhiverypickuprequest',
            name='pickup_location',
            field=models.CharField(db_index=True, default=datetime.datetime(2025, 12, 16, 13, 51, 30, 981375, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='delhiverypickuprequest',
            unique_together={('pickup_date', 'slot', 'pickup_location')},
        ),
    ]
